project : c:\projects\gkit\lib\gkit.lib c:\projects\gkit\demos\animdemo.exe &
c:\projects\gkit\demos\kbddemo.exe c:\projects\gkit\demos\vbmtest.exe c:\pro&
jects\gkit\demos\mousedmo.exe c:\projects\gkit\utils\palmaker.exe c:\project&
s\gkit\utils\archmake.exe c:\projects\gkit\utils\pcx2vbm.exe c:\projects\gki&
t\utils\vbmview.exe .SYMBOLIC

!include c:\projects\gkit\lib\gkit.mk1
!include c:\projects\gkit\demos\animdemo.mk1
!include c:\projects\gkit\demos\kbddemo.mk1
!include c:\projects\gkit\demos\vbmtest.mk1
!include c:\projects\gkit\demos\mousedmo.mk1
!include c:\projects\gkit\utils\palmaker.mk1
!include c:\projects\gkit\utils\archmake.mk1
!include c:\projects\gkit\utils\pcx2vbm.mk1
!include c:\projects\gkit\utils\vbmview.mk1
